{% set name = "dspsr" %}
{% set version = "2024-08-01" %}
{% set sha256 = "7db30c9e8c95e496b83210275c178d54027f605bf0c29db43cb74a599e9563b5" %}

package:
    name: "{{ name | lower }}"
    version: "{{ version | replace('-','.') }}"

source:
    url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - strip_emutls_w.patch  # [osx]
        - macos_fmemopen.patch  # [osx]
        - dmsmear.patch  # [osx]
        - test_util.patch
        - shell_for_flags.patch
        
build:
    number: 0
    skip: true  # [win or (python_impl == 'pypy')]
    run_exports:
      - {{ pin_subpackage('dspsr', exact=True) }}

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make
        - perl
        - autoconf
        - automake
        - libtool
        - pkg-config
        - swig  # [linux]
    host:
        - psrchive
        - cfitsio
        - pgplot
        - python {{ python }}  # [linux]
        - numpy  # [linux]
    run:
        - {{ pin_compatible('psrchive', exact=True) }}
        - cfitsio
        - {{ pin_compatible('pgplot') }}
        - python  # [linux]
        - {{ pin_compatible('numpy') }}  # [linux]

test:
    commands:
        - digifil -h
        - digifits -h
        - digihdr -h
        - digihist -h
        - digimon -h
        - digistat -h
        - digitxt -h
        - dmsmear -h  # [not osx]
        - dspsr -h
        - dspsr_cflags
        - dspsr_ldflags
        - filterbank_speed -h
        - load_bits -h
        - passband -h
        - searchplot -h
        - sk_distrib_plot -h
        - sklimit -h
        - sk_limit_plot -h
        - t2pred -h
        - test -f $PREFIX/lib/libdspbase$SHLIB_EXT
        - test -f $PREFIX/lib/libdspdsp$SHLIB_EXT
        - test -f $PREFIX/lib/libdspsrmore$SHLIB_EXT
        - test -f $PREFIX/lib/libdspsr$SHLIB_EXT
        - test -f $PREFIX/lib/libdspstats$SHLIB_EXT
        - test -f $PREFIX/include/dspsr/dsp/dsp.h
    imports:
        - dspsr  # [linux]

about:
    home: http://dspsr.sourceforge.net/
    license: AFL-2.1
    license_file: LICENSE
    summary: DSPSR is a library for digital signal processing of pulsar astronomical timeseries.
    dev_url: http://sourceforge.net/projects/dspsr/

extra:
    recipe-maintainers:
        - demorest
        - straten
